// Se crean las variables para definir las request que se haran en la DB
export const GET_DOGS = 'GET_DOGS'
export const GET_DOGS_NAME = 'GET_DOGS_NAME'
export const POST_DOGS = 'POST_DOGS'
export const PUT_DOGS = 'PUT_DOGS'
export const DELETE_DOGS = 'DELETE_DOGS'
export const DETAIL_DOGS = 'DETAIL_DOGS'
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'
export const DESCENDING_SORT = 'DESCENDING_SORT'
export const ASCENTDANT_SORT = 'ASCENTDANT_SORT'
export const WEIGHT_MIN = 'WEIGHT_MIN'
export const WEIGHT_MAX = 'WEIGHT_MAX'
export const TEMP = 'TEMP'
export const API = 'API'
export const DB = 'DB'
export const REFRESH = 'REFRESH'
export const RESET = 'RESET'
export const REFRESH_MSG = 'REFRESH_MSG'