export const GET_DOGS = 'GET_DOGS'
export const POST_DOGS = 'POST_DOGS'
export const PUT_DOGS = 'PUT_DOGS'
export const DELETE_DOGS = 'DELETE_DOGS'
export const DETAIL_DOGS = 'DETAIL_DOGS'
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'
